### PR TITLE
Archon Compatibility with PHP 5.5 and PHP 5.6

### PR DESCRIPTION
**Pull request by cvonkleist**
Hi, Chris Prom and other maintainers of Archon! This rather large pull request makes Archon compatible with PHP 5.5 and PHP 5.6 (while maintaining compatibility with earlier versions of PHP, such as PHP 5.3).

We'd really love it if the Archon maintainers would consider merging this into the official repository.

* * * * *

This code was tested throughout development to ensure its behavior is identical to that of Archon v3.21.2.1, the most recent official release, so we believe it is safe to merge into the official repo. (Our verification process: We ran a set of 1,000+ HTTP queries against the new code and compared the HTTP responses to those of the official release. The HTTP queries were recorded from the activity of a real user who tried to exercise all of Archon's functionality.) This code is currently running in production on some of LibraryHost's servers and at two institutions who participated in the Archon Update Project.

* * * * *

Here's a guide to the changes in this pull request:

- Primary goal:
  - Prevent errors and silence warnings when running with PHP 5.5 and 5.6 (while maintaining compatibility with PHP 5.3)
    - Explicitly create new objects instead of creating them implicitly on access via nested `->` operators
    - Do explicit type casting where PHP warned about implicit casts
    - Don't call PEAR::isError object method as a function
    - Use PHP MySQLi extension (MySQL Improve) instead of MySQL extension (MySQL Original) which was deprecated in PHP 5.5
      - Fix problem in packages/digitallibrary/lib/file.inc.php that made it impossible to retrieve some digital objects from MySQL due to null bytes
      - Explicitly set MySQLi charset to UTF-8
    - etc.
- Other changes:
  - Improve README.md:
    - Add Markdown formatting
    - Add a README.advanced.md with quick instructions for sysadmins on Ubuntu
  - Document how to install ModSecurity with Archon
  - Support partial search for collection identifier (by Syed Nouman Tayyab of AVPreserve)

(This code was developed as part of the "Archon Update Project", a group effort by Denison University, LibraryHost.com, Berea College, Luther College, Oberlin College, Southern Illinois University Carbondale, and Wheaton College.)

### CODE REVIEW

**Comment by chrisprom** [comment]
Thanks so much @cvonkleist and everyone involved with this project.  I will review this as soon as I can find some time outside of work hours to focus on it.   

Before delving into this, I do have one question: does this new code still support MSSQL-- Microsoft SQL server--and if so did you test it with that?   Abstraction to MSSQL was through the MDB2 Library, so any changes there???

**Comment by cvonkleist** [comment]
Hi, @chrisprom. Thank you very much.

Unfortunately, we did not test the changes with MSSQL. MSSQL should still be supported just fine by the MDB2 library. However, I can think of one spot in the new code that might cause a problem for MSSQL. We use the `HEX()` function to get file data out of the database in a way that doesn't cause unicode misinterpretations:

```php
$query = "SELECT HEX(SUBSTRING({$_ARCHON->mdb2->quoteIdentifier($this->fpointer)}, ?, ?)) as FilePacket FROM tblDigitalLibrary_Files WHERE ID = ?";
```

I didn't think about this until you mentioned MSSQL, but I don't think MSSQL has the `HEX()` function.

https://github.com/archonproject/archon/pull/76/commits/6958fc96dd5ecb9524658138879e1d10858259ff#diff-6456563b57951f844a99b1b4a4a5f846R750

**Comment by chrisprom** [comment]
Thanks.  I will test for that and see if we can find a way around it.

Chris Prom
chris.prom@gmail.com

**Comment by chrisprom** [comment]
This works with Microsoft SQL server under php 5.3.3, but only with some slight modifications to three files to three files: start.inc.php, packages/core/lib.archon.inc.php, and packages/digitallibrary/lib/file.inc.php.  

I will review next under other versions of php and with various database configurations.

**Pull request merged**
